project:
  type: website
  output-dir: docs

website:
  title: "Peter Laurin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: resources.qmd
        text: Resources
      - href: posts.qmd
        text: Blog



format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

